name: Code Style

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: switch base docker image
      run: sed -i -e 's|FROM archlinux/base|FROM actionless/pikaur|' Dockerfile

    - name: build docker image
      run: docker image build ./ -t oomoxify

    - name: run tests in docker
      run: docker run --entrypoint ./shellcheck.sh oomoxify:latest
